# Use root/example as user/password credentials
version: "3.1"

services:
  postgres:
    image: postgres
    volumes:
      - ./prod-settings/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - /home/nicolas/.ezwn-boardgames/postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  boardgames-backend:
    image: boardgames-backend:0.6
    volumes:
      - ./prod-settings/application.properties:/application.properties
    restart: always
    ports:
      - 8080:8180
        
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    
#  boardgames-frontend:
#    image: boardgames-frontend:0.6
#    restart: always
#    ports:
#      - 8081:5000
